# Generated by Django 3.1.2 on 2020-10-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Кличка')),
                ('age', models.SmallIntegerField(verbose_name='Возраст')),
                ('arrived', models.DateField(auto_now_add=True, verbose_name='Дата прибытия в приют')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('height', models.SmallIntegerField(verbose_name='Рост')),
                ('special_sigh', models.CharField(max_length=255, verbose_name='Особые приметы')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
    ]
