# Generated by Django 3.1.2 on 2020-10-18 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='height',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='special_sigh',
            field=models.CharField(blank=True, max_length=255, verbose_name='Особые приметы'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес'),
        ),
    ]
