# Generated by Django 3.1.2 on 2020-10-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20201018_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='shelter',
            options={'verbose_name': 'Приют', 'verbose_name_plural': 'Приюты'},
        ),
    ]
