# Generated by Django 3.1.2 on 2020-10-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20201018_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
