# Generated by Django 3.1.2 on 2020-10-19 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_pet_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.AddField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(default=datetime.date(2020, 10, 19), verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='arrived',
            field=models.DateField(default=datetime.date(2020, 10, 19), verbose_name='Дата прибытия в приют'),
        ),
    ]
